name: TDLib Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install dependency
      run: |
        sudo apt-get install gperf cmake build-essential libssl-dev zlib1g-dev

    - name: download code
      run: |
        git clone https://github.com/tdlib/td.git
        cd td && git submodule update --init --recursive

    - name: cmake
      run: |
        mkdir td/build
        cd td/build && cmake -DCMAKE_BUILD_TYPE=Release ..
        cd td/build && cmake --build .
